"""Repair the shelf pages' own presentation layer.

Two defects live in the archived shelf pages, both of which make a page look
broken while every link on it still works:

1. An orphaned stylesheet. Some pages lost the opening ``<style>`` tag, so the
   20-odd kilobytes of CSS that follow sit in ``<head>`` as bare text. The
   browser never applies it and the page renders unstyled, and the stray
   ``</style>`` is silently ignored. Every ``class`` in the markup becomes
   meaningless.

2. A mangled glyph. One heading lost its emoji to an encoding round-trip and
   arrived as two literal ``?`` characters. The page is internally consistent,
   so the correct glyph can be read off its siblings rather than guessed.

Both are repairable without touching prose, code or structure: the CSS is
restored exactly as written, and the glyph is taken from the file itself.

Idempotent. ``--dry`` reports without writing.
"""

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(r"C:\Users\user\Desktop\the_books")
BOOKS = ["data_science", "finance", "geomatics", "operations_research"]

STYLE_OPEN = re.compile(r"<style\b", re.I)
STYLE_CLOSE = re.compile(r"</style\s*>", re.I)
# A line that starts markup rather than CSS. Walking back over the CSS run stops
# at the first of these, which is how the run's beginning is found: a run of
# declarations has no tag at the start of any of its lines.
MARKUP_LINE = re.compile(r"^\s*(?:<!--|</?[a-zA-Z!])")
# A heading whose leading glyph did not survive.
MANGLED = re.compile(r"(?:<h[1-6][^>]*>|<span class=\"label\">)(\s*)\?\?")


def repair_stylesheet(text: str, counts: Counter) -> str:
    """Give an orphaned ``</style>`` the ``<style>`` it lost."""
    opens = list(STYLE_OPEN.finditer(text))
    closes = list(STYLE_CLOSE.finditer(text))
    if len(opens) >= len(closes):
        return text

    # The closes with no opener before them are the orphans. The last one ends
    # the CSS run that lost its <style>; that run is what needs wrapping.
    orphans = [m for m in closes if not any(o.start() < m.start() for o in opens)]
    if not orphans:
        return text
    orphan = orphans[-1]

    before = text[: orphan.start()]
    after = text[orphan.start():]  # keeps the orphan's own </style> and everything after

    # Walk back over the CSS the orphan </style> was meant to close. The run ends
    # at the last line that is not markup.
    lines = before.splitlines(keepends=True)
    start = len(lines)
    while start > 0 and not MARKUP_LINE.match(lines[start - 1]):
        start -= 1
    run = "".join(lines[start:])
    if start == len(lines) or "{" not in run or start == 0:
        return text  # nothing recognisable to wrap; leave it for a human
    if STYLE_OPEN.search(run):
        return text  # the run is already inside a style element

    counts["restored-orphaned-stylesheet"] += len(orphans)
    counts["restored-stylesheet-chars"] += len(run)
    return "".join(lines[:start]) + "<style>\n" + run + after


def repair_mangled_glyph(text: str, counts: Counter) -> str:
    """Restore a heading glyph that the file's own siblings agree on."""
    if "??" not in text:
        return text

    # Read the intended glyph off the file rather than guessing it. The other
    # headings of the same kind name it, so the majority wins.
    siblings = Counter(re.findall(r"<h4>\s*(\S+)\s+Worked Example", text))
    if not siblings:
        siblings = Counter(re.findall(r'<span class="label">\s*(\S+)\s', text))
    siblings.pop("??", None)
    if not siblings:
        return text
    glyph, agree = siblings.most_common(1)[0]
    if agree < 2:
        return text  # one voice is not a consensus

    counts["restored-mangled-glyph"] += text.count("??")
    return text.replace("??", glyph)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry", action="store_true", help="report without writing")
    args = ap.parse_args()

    counts: Counter = Counter()
    changed: list[str] = []

    for book in BOOKS:
        for path in sorted((ROOT / book / "mixed_shelf").glob("*.html")):
            if path.name == "index.html":
                continue  # generated by build_book_nav.py
            original = path.read_text(encoding="utf-8")

            text = repair_stylesheet(original, counts)
            text = repair_mangled_glyph(text, counts)
            if text != original:
                changed.append(f"{book}/{path.name}")
                if not args.dry:
                    path.write_text(text, encoding="utf-8")

    if not changed:
        print("Nothing to do; every shelf page already carries its stylesheet.")
        return 0

    verb = "would repair" if args.dry else "repaired"
    for book in BOOKS:
        n = sum(1 for name in changed if name.startswith(f"{book}/"))
        if n:
            print(f"{book:20} {verb} {n:3} page(s)")

    print()
    for k, v in counts.most_common():
        print(f"    {v:>4}  {k}")
    print(f"\n{verb} {len(changed)} page(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
